"""empty message

Revision ID: 1a98277d11e9
Revises: 38ee25ca93dd
Create Date: 2021-04-27 08:01:23.815399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a98277d11e9'
down_revision = '38ee25ca93dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'about_me_long',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'about_me_short',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'profile_photo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_photo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('user', 'about_me_short',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'about_me_long',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
