"""empty message

Revision ID: 8a31e8931cbc
Revises: 286c081c36ee
Create Date: 2021-04-29 15:45:06.789509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a31e8931cbc'
down_revision = '286c081c36ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buddy', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('comment', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('comment', 'create_at')
    op.drop_column('reservation', 'create_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('comment', 'created_at')
    op.drop_column('buddy', 'created_at')
    # ### end Alembic commands ###
